name: DevSecOpes end to end pipeline

on:
    push:
        branches: [main]   

jobs:
    # CI (continous integration with security scanning)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrats-scan:
         uses: ./.github/workflows/secrats-scan.yml

    dependancy-scan:
         uses: ./.github/workflows/dependancy-scan.yml
         
    docker-scan:
         uses: ./.github/workflows/docker-lint.yml
      
         # build ones the security scans are complete
    build:
        needs: [code-quality, secrats-scan, dependancy-scan, docker-scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    trivy:
         needs: [build]
         uses: ./.github/workflows/image-scan.yml
         secrets: inherit